# Generated by Django 5.2.2 on 2025-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otc',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
