# Generated by Django 5.2.2 on 2025-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_user_otc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
